// Hypotheses de rendement annuel moyen (nominal, en %) et volatilite (ecart-type annuel)
// basees sur les moyennes historiques long terme. Ce sont des estimations indicatives,
// pas des garanties : les performances passees ne prejugent pas des performances futures.

export const PRESETS = [
  {
    id: 'sp500',
    name: 'S&P 500',
    emoji: '🇺🇸',
    desc: '500 plus grandes entreprises americaines',
    meanReturn: 9.5, // % / an nominal
    volatility: 15,
    ter: 0.07, // frais annuels du tracker en %
    color: '#4f7cac',
  },
  {
    id: 'msci-world',
    name: 'MSCI World',
    emoji: '🌍',
    desc: 'Actions des pays developpes (~1500 entreprises)',
    meanReturn: 8.5,
    volatility: 14,
    ter: 0.2,
    color: '#5e9f73',
  },
  {
    id: 'nasdaq100',
    name: 'Nasdaq 100',
    emoji: '💻',
    desc: '100 plus grosses valeurs tech US (volatil)',
    meanReturn: 12,
    volatility: 20,
    ter: 0.3,
    color: '#7c6baf',
  },
  {
    id: 'stoxx600',
    name: 'STOXX Europe 600',
    emoji: '🇪🇺',
    desc: '600 entreprises europeennes',
    meanReturn: 7,
    volatility: 14,
    ter: 0.2,
    color: '#4f9cac',
  },
  {
    id: 'emerging',
    name: 'Marches emergents',
    emoji: '📈',
    desc: 'MSCI Emerging Markets (Chine, Inde, etc.)',
    meanReturn: 7.5,
    volatility: 18,
    ter: 0.18,
    color: '#c98b5d',
  },
  {
    id: 'world-acc',
    name: 'Monde + Emergents (ACWI)',
    emoji: '🌐',
    desc: 'Actions mondiales developpees + emergentes',
    meanReturn: 8,
    volatility: 15,
    ter: 0.2,
    color: '#5e9f8f',
  },
  {
    id: 'gold',
    name: 'Or',
    emoji: '🥇',
    desc: 'Valeur refuge, decorrele des actions',
    meanReturn: 6,
    volatility: 15,
    ter: 0.4,
    color: '#d4b46a',
  },
  {
    id: 'bonds',
    name: 'Obligations',
    emoji: '🏛️',
    desc: "Dette d'Etat / entreprises, peu volatil",
    meanReturn: 3.5,
    volatility: 6,
    ter: 0.15,
    color: '#7d8596',
  },
  {
    id: 'scpi',
    name: 'Immobilier (SCPI)',
    emoji: '🏢',
    desc: 'Pierre-papier, loyers reguliers',
    meanReturn: 4.5,
    volatility: 8,
    ter: 1.0,
    color: '#ac6b8b',
  },
  {
    id: 'fonds-euro',
    name: 'Fonds euro (assurance-vie)',
    emoji: '🛡️',
    desc: 'Capital garanti, rendement faible',
    meanReturn: 2.8,
    volatility: 1,
    ter: 0.6,
    color: '#c9a85d',
  },
  {
    id: 'livret-a',
    name: 'Livret A',
    emoji: '🐷',
    desc: 'Epargne sans risque, plafonnee',
    meanReturn: 2.4,
    volatility: 0,
    ter: 0,
    color: '#9aa0a8',
  },
  {
    id: 'crypto',
    name: 'Crypto (BTC)',
    emoji: '₿',
    desc: 'Tres speculatif, volatilite extreme',
    meanReturn: 18,
    volatility: 60,
    ter: 0,
    color: '#c98b5d',
  },
  {
    id: 'custom',
    name: 'Personnalise',
    emoji: '⚙️',
    desc: 'Definis ton propre rendement',
    meanReturn: 6,
    volatility: 10,
    ter: 0,
    color: '#6e8baf',
  },
];

export function getPreset(id) {
  return PRESETS.find((p) => p.id === id) || PRESETS[0];
}
